<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KeepersCompound.Formats\KeepersCompound.Formats.csproj" />
    <ProjectReference Include="..\KeepersCompound.Dark.Maths\KeepersCompound.Dark.Maths.csproj" />
  </ItemGroup>

</Project>
